# Setup parameters
setup:
  test_id: simclr_2
  seed: 1
  num_workers: 0
  num_epochs: 30  ##check max_epochs

# Hyperparameters
hyperparameters:
  batch_size: 128 # 128 x 4 gpus = 512
  temperature: 0.1
  optimizer:
    lr: 0.6
    momentum: 0.9
    weight_decay: 0.000001
    nesterov: False
  scheduler:
    warmup_epochs: 10
    max_epochs: 30 ##check num_epochs
    warmup_start_lr: 0.15
    eta_min: 0.0015

# Model parameters
model:
  arch: "resnet18"
  num_ftrs: 512
  out_dim: 128

# Augmentations:
transforms:
  img_crop_size: 380
  cjitter: 
    brightness: [0.4, 1.3]
    contrast: 0.6
    saturation: 0.6
    hue: 0.4
  cjitter_p: 1.0
  randaffine:
    degrees: 10
    translate: [0.2, 0.2]
    scale: [1.3, 1.4]
    shear: 1.0
  randpersp:
    distortion_scale: 0.1
    p: 0.2
  gray_p: 0.2
  gaussian_blur:
    kernel_size: 3
    sigma: [0.1, 0.5]
  rand_eras:
    p: 0.5
    scale: [0.02, 0.33]
    ratio: [0.3, 3.3]
    value: 0
  invert_p: 0.05
